spring:
  flyway:
    url: jdbc:h2:mem:controle-obras;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    locations: classpath:db/migration
    default-schema: FLYWAY
    user: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect: PostgreSQLDialect
  data:
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:h2:mem:controle-obras;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver