CREATE TABLE CONTROLE_OBRAS.PESSOAS (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NOME CHARACTER VARYING(100),
    CPF CHARACTER VARYING(100),
    EMAIL CHARACTER VARYING(100),
    ATIVO BOOLEAN,
    CONSTRAINT PESSOAS_PK PRIMARY KEY (ID)
);